#!/bin/bash
# ============================================================
# benign_file_transfer.sh
# Traffic Type: Normal file transfers (scp)
# Source: Ubuntu Server VM (192.168.10.4)
# Target: Metasploitable (192.168.30.20)
#
# Simulates normal file transfers between systems — the kind
# of bulk TCP traffic generated by backups, deployments,
# or routine file sharing. Very different flow characteristics
# from attack traffic: large sustained flows, high throughput,
# long duration, completes cleanly.
#
# Usage: bash benign-file-transfer.sh
# Log in session_log.csv: label=benign, scenario=benign_file_transfer
# ============================================================

TARGET_IP="192.168.30.20"
TARGET_USER="msfadmin"
TARGET_PASS="msfadmin"
TEMP_DIR="/tmp/benign_transfers"

mkdir -p "$TEMP_DIR"

if ! command -v sshpass &> /dev/null; then
    sudo apt-get install -y sshpass > /dev/null 2>&1
fi

SCP_OPTS="-o StrictHostKeyChecking=no -o ConnectTimeout=5"

echo "============================================"
echo " Benign File Transfer Simulation"
echo " Started: $(date '+%Y-%m-%d %H:%M:%S')"
echo " Target: ${TARGET_USER}@${TARGET_IP}"
echo "============================================"
echo "[!] Record start time in session_log.csv"
echo ""

TRANSFER_COUNT=0

for i in $(seq 1 6); do
    # Generate files of varying sizes (10KB to 2MB)
    # Simulates transferring config files, logs, backups, scripts
    SIZE_KB=$((RANDOM % 2000 + 10))
    FILENAME="${TEMP_DIR}/transfer_file_${i}.dat"

    echo "[*] Transfer $i — generating ${SIZE_KB}KB file..."
    dd if=/dev/urandom of="$FILENAME" bs=1024 count="$SIZE_KB" 2>/dev/null

    # Upload file to target
    echo "  [*] Uploading to ${TARGET_IP}..."
    sshpass -p "$TARGET_PASS" scp $SCP_OPTS \
        "$FILENAME" \
        "${TARGET_USER}@${TARGET_IP}:/tmp/" 2>/dev/null

    # Download a file back (simulates bidirectional transfer)
    echo "  [*] Downloading from ${TARGET_IP}..."
    sshpass -p "$TARGET_PASS" scp $SCP_OPTS \
        "${TARGET_USER}@${TARGET_IP}:/etc/passwd" \
        "${TEMP_DIR}/downloaded_${i}.txt" 2>/dev/null

    TRANSFER_COUNT=$((TRANSFER_COUNT + 1))
    rm -f "$FILENAME"

    # Realistic pause between transfers
    sleep $((RANDOM % 20 + 10))
done

# Cleanup
rm -rf "$TEMP_DIR"

echo ""
echo "============================================"
echo " Complete: $(date '+%Y-%m-%d %H:%M:%S')"
echo " Total transfers: ${TRANSFER_COUNT}"
echo "============================================"
echo "[!] Record end time in session_log.csv"
echo "[!] Label: benign | Scenario: benign_file_transfer"
